config/routes.rb
TestCheckout::Application.routes.draw do

  resources :checkouts, :except => [:show, :edit, :update] do
    member do
      get 'scan'
      get 'total'
    end
  end

  resources :transactions, :only => [:create]

  root :to => 'checkouts#index'

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base

  has_many :transactions
  has_and_belongs_to_many :pricing_rules

  def total
    total = 0
    for transaction in self.transactions do
      total += transaction.product.price * transaction.no_of_items
    end
    for pricing_rule in self.pricing_rules do
      if pricing_rule.discount_type == "bogof"
        item_count = self.transactions.select{|i| i.product_id == pricing_rule.product_id}.length
        total -= (item_count/2).to_i*pricing_rule.product.price
      else
        item_count = self.transactions.select{|i| i.product_id == pricing_rule.product_id}.length
        if item_count >= pricing_rule.bulk_threshold
          total -= item_count*(pricing_rule.product.price - pricing_rule.bulk_price)
        end
      end
    end
    total
  end

end

app/models/pricing_rule.rb
class PricingRule < ActiveRecord::Base

  VALID_TYPES = %w(bogof bulk)

  validates_presence_of :discount_type, :product
  validates_inclusion_of :discount_type, :in => VALID_TYPES

  belongs_to :product
  has_and_belongs_to_many :checkouts

  def description
    if self.discount_type == "bulk"
      "#{product.name} #{discount_type}(#{bulk_threshold}) at #{bulk_price}"
    else
      "#{product.name} #{discount_type}"
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :product_code, :price
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates_presence_of :product, :checkout, :no_of_items
  belongs_to :checkout
  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  #GET /checkouts
  #GET /checkouts.json
  def index
    @checkouts = Checkout.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkouts }
    end
  end

  #GET /checkouts/new
  #GET /checkouts/new.json
  def new
    @checkout = Checkout.new
    @pricing_rules = PricingRule.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkout }
    end
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      if @checkout.save
        format.html { redirect_to scan_checkout_path(@checkout), notice: 'Checkout was successfully created.' }
        format.json { render json: @checkout, status: :created, location: @checkout }
      else
        format.html { render action: "new" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end

  def scan
    @checkout = Checkout.find(params[:id])
    @products = Product.all
    @transaction = Transaction.new
  end

  def total
    @checkout = Checkout.find(params[:id])
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    @transaction = Transaction.new(params[:transaction])
    if @transaction.save
      redirect_to :back, :notice => 'Transaction added.'
    else
      redirect_to :back, :notice => 'Opps, something went wrong. Try again.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/views/checkouts/_add_item_form.html.haml
%tr{:id => product.product_code}
  %td= product.product_code
  %td= product.name
  %td= product.price
  %td
    = form_for @transaction do |f|
      .field
        = f.hidden_field :checkout_id, :value => @checkout.id
      .field
        = f.hidden_field :product_id, :value => product.id
      .field
        = f.hidden_field :no_of_items, :value => 1
      .actions
        = f.submit 'Add'

app/views/checkouts/_form.html.haml
= form_for @checkout do |f|
  -if @checkout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@checkout.errors.count, "error")} prohibited this checkout from being saved:"
      %ul
        - @checkout.errors.full_messages.each do |msg|
          %li= msg
  %p Select the pricing rules for this checkout:
  = f.collection_select :pricing_rule_ids, @pricing_rules, :id, :description, {}, { :selected => @checkout.pricing_rule_ids, :multiple => true }
  %p TODO add new if not present above
  .actions
    = f.submit 'Save'

app/views/checkouts/_receipt_content.html.haml
%h1= "Checkout ID #{@checkout.id}"
%h2 Applied pricing rules
%ul{:id => "pricing_rules"}
  - if @checkout.pricing_rules.length > 0
    - for pricing_rule in @checkout.pricing_rules do
      %li= pricing_rule.description.html_safe
  -else
    %li None
%h2 Transactions
%ul{:id => "transactions"}
  - if @checkout.transactions.length > 0
    - for transaction in @checkout.transactions do
      %li= "#{transaction.no_of_items} #{transaction.product.name}"
  -else
    %li None

app/views/checkouts/index.html.haml
%h1 Listing checkouts

%table
  %tr
    %th
    %th
    %th
    %th

  - @checkouts.each do |checkout|
    %tr
      %td= checkout.id
      %td= link_to 'Scan', scan_checkout_path(checkout)
      %td= link_to 'Total', total_checkout_path(checkout)
      %td= link_to 'Destroy', checkout, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Checkout', new_checkout_path

app/views/checkouts/new.html.haml
%h1 New checkout

= render 'form'


= link_to 'Index', checkouts_path

app/views/checkouts/scan.html.haml
%p#notice= notice

= render "receipt_content"

%h2= link_to 'Total', total_checkout_path(@checkout)

%h1 Available Products

%table
  %tr
    %th Product Code
    %th Name
    %th Price
    %th
  - for product in @products do
    = render "add_item_form", :product => product


%p= link_to 'Index', checkouts_path

app/views/checkouts/total.html.haml
%p#notice= notice

= render "receipt_content"


%h2= "TOTAL: #{@checkout.total}"


= link_to 'Destroy', @checkout, :confirm => 'Are you sure?', :method => :delete
\|
= link_to 'Index', checkouts_path
\|
= link_to 'New Checkout', new_checkout_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestCheckout</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>